spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 10s
  application:
    name: user
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9004

zkServer:
  name: test
  server: 192.168.198.129:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 6000
  maxRetries: 3
  baseSleepTimeMs: 1000